/*Use (connect to) your database - you MUST update xyz001
 with youur authcate username*/
use ("xyz001");

/*12.1.2 MongoDB Create Update and Delete */

/*2. Name the collection as enrolment (you may use any suitable name for your database) 
and insert the first 10 documents generated by the select statement into MongoDB
 */


/*3. Create a new enrolment for studid 12489379, the student is enrolled in FIT2002 
(IT Project Management) in semester 1 2022. Since this is a new enrolment, 
set the mark and the grade as null.*/


/*4. Update this enrolment for studid 12489379 in FIT2002, 
set the mark to 65 and grade to C*/

/*5. Delete this enrolment for student id 12489379 in FIT2002 */


/*-----------------------------------------------------------*/
/*12.1.3 MongoDB Read
Write db.find() commands for following questions:*/

/*1. Retrieve the document for student id = 12802225*/

/*2. Show the id and name of students who have any mark greater than 95 in any enrolment (hint: use $gt:95)*/

/*3. Retrieve the name and contact info of students who enrolled in any unit which has "web design" as part of its name*/

/*4. Retrieve the  id and name of any students who have grades WH or N*/


